HMP2_CONTIGS_URLS_FILE = "hmp2_contigs_urls"
HMP2_PILOT_CONTIGS_URLS_FILE = "hmp2_pilot_contigs_urls"
CONTIGS_DOWNLOADS_DIR = "genomes/downloads/contigs"
CONTIGS_DIR = "genomes/contigs"
HMP2_GENE_CALLS_URLS_FILE = "hmp2_gene_calls_urls"
HMP2_PILOT_GENE_CALLS_URLS_FILE = "hmp2_pilot_gene_calls_urls"
GENE_CALLS_DOWNLOADS_DIR = "genomes/downloads/gene_calls"
GENE_CALLS_DIR = "genomes/gene_calls"
AA_SEQUENCES_DIR = "genomes/aa_sequences"
NT_SEQUENCES_DIR = "genomes/nt_sequences"

RESULTS_DIR = "genomes/results"
COMPLETE_SEQUENCES = "genomes/results/complete_sequences.fasta"
PARTIAL_SEQUENCES = "genomes/results/partial_sequences.fasta"


SEQUENCE_FREQUENCIES = "genomes/results/sequence_frequencies"
PARTIAL_CONTAINED = "genomes/results/partial_contained"
PARTIAL_COLLAPSED = "genomes/results/partial_collapsed"
PARTIAL_UNCOLLAPSED = "genomes/results/partial_uncollapsed"